{"name":"feature","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"java.lang.AssertionError: expected [Create New Account] but found [Log In]","trace":"cucumber.runtime.CucumberException: java.lang.AssertionError: expected [Create New Account] but found [Log In]\n\tat cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)\n\tat com.fblogin.testrunner.TestRunners.feature(TestRunners.java:38)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:564)\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)\n\tat org.testng.internal.Invoker.invokeMethod(Invoker.java:583)\n\tat org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)\n\tat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)\n\tat org.testng.TestRunner.privateRun(TestRunner.java:648)\n\tat org.testng.TestRunner.run(TestRunner.java:505)\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:455)\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:364)\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1137)\n\tat org.testng.TestNG.runSuites(TestNG.java:1049)\n\tat org.testng.TestNG.run(TestNG.java:1017)\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)\nCaused by: java.lang.AssertionError: expected [Create New Account] but found [Log In]\n\tat org.testng.Assert.fail(Assert.java:96)\n\tat org.testng.Assert.failNotEquals(Assert.java:776)\n\tat org.testng.Assert.assertEqualsImpl(Assert.java:137)\n\tat org.testng.Assert.assertEquals(Assert.java:118)\n\tat org.testng.Assert.assertEquals(Assert.java:453)\n\tat org.testng.Assert.assertEquals(Assert.java:463)\n\tat com.fblogin.tests.testcases.TestCases.assertProjectXpath(TestCases.java:29)\n\tat com.fblogin.tests.testcases.TestCases.validateFbPage(TestCases.java:33)\n\tat com.fblogin.stepsdefinition.FacebookStepDefinition.createNewAccount(FacebookStepDefinition.java:55)\n\tat âœ½.Then Create New Account(FacebookLogin.feature:9)\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[{"name":"arg0","value":"Facebook wrong password login failure validation"}],"start":1621930177469,"stop":1621930186994,"uuid":"d6ec5e5f-4b37-493a-b354-a1f4177569a2","historyId":"7de3436529f22bd50b51ed9e5eafd264","fullName":"com.fblogin.testrunner.TestRunners.feature","labels":[{"name":"package","value":"com.fblogin.testrunner.TestRunners"},{"name":"testClass","value":"com.fblogin.testrunner.TestRunners"},{"name":"testMethod","value":"feature"},{"name":"parentSuite","value":"All Test Suite"},{"name":"suite","value":"/Users/kehindeadeoya/Documents/projects/FBLogin/src/com/fblogin/testrunner/TestRunner.java"},{"name":"subSuite","value":"com.fblogin.testrunner.TestRunners"},{"name":"host","value":"wikiwoos-MacBook-Pro.local"},{"name":"thread","value":"11877@wikiwoos-MacBook-Pro.local.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[]}